name: Python CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check ."
